export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED'


export const GET_BY_CATEGORY = 'GET_BY_CATEGORY'
export const GET_BY_CATEGORY_SUCCESS = 'GET_BY_CATEGORY_SUCCESS'
export const GET_BY_CATEGORY_FAILED = 'GET_BY_CATEGORY_FAILED'




